### ISSUE TITLE
read commit comments on github, uint64 vs pointer oddities you should be aware of. Pointer type information. Void pointer.

### ISSUE THREAD

**Issue by gek169** [rizet/skylight#3]
0) Thanks for fixing those bugs I told you about.

1) I've made some comments on your commits, I didn't spot any critical bugs, but I spotted several bits of... "unusual" practice.

2) You should be aware that pointers on most x86_64 machines have a special property... the 48th bit is repeated through the upper quarter of the integer. The pointers are actually only 48 bits (bits 48-63 are repeats of bit 47, if bit 0 is the first bit) When you discard the pointer type and use uint64_t, the type system can't preserve this intriguing fact.

I didn't spot anywhere in your code where this fact would give you a bug, but you're intentionally punning away pointer classification to uint64_t which I foresee down the line is gonna cause issues for this very reason. This is also just bad practice.

HUGE NOTE: this 48 bit property is NOT in the spec for x86_64 it is merely a fact for x86_64 arches we have today. the spec says those other 16 bits can be used in the future... so don't go storing your pointers in 6 bytes for efficiency either.

a pointer will be 8 bytes and you don't need to worry about the compiler ruining your packed structs. No, the compiler won't remove the unused 16 bits (... if it does, then please tell me, that would be a very interesting bug report...)

3) You should know that void pointer arithmetic is a gnu extension. I know you said you only ever compiled with clang, but believe me, you will most likely regret this decision later.

4) You can have a struct with a member pointer to itself (In the standard)
```c
typedef struct myStruct{
    struct myStruct* next;
    struct myStruct* previous;
    unsigned char data;
} myStruct;
```
This is valid C syntax. I think it's even in the C89 standard as an example for implementers (iirc) so every compiler on earth will do the right thing.

**Comment by gek169** [comment]
I'd like to clarify that I think you can resolve these issues rather simply just by replacing uint64_t's that are "secretly" pointers with `void*`
Of course, this is still not very good practice since the type of the pointed-to element is not preserved, but it will guarantee expected pointer behavior.

Void pointer arithmetic is defined in clang and if you really intend to only use that going forward, then that's fine, but you *can* use `unsigned char*` in place of void* if you really want the compiler-friendly code.

I'm still thinking about whether or not the 48 bit virtual address space of x86_64 machines is causing any bugs in the code i've seen. I'm still not sure. I don't know enough about osdev to verify your TLB/MMU setup code

**Comment by rizet** [comment]
At the moment, it is not causing any bugs that I am aware of. However, I have labeled this issue with "impactful ub" because it has caused issues in the past.

**Comment by gek169** [comment]
I don't see any bugs either, but I think the potential for bugs can be eliminated rather swiftly

**Comment by rizet** [comment]
Due to the scope of this issue, and the minimal risk involved with current procedures, I am closing this issue and disregarding it.
