### ISSUE TITLE
strcmp bug if char is unsigned

### ISSUE THREAD

**Issue by gek169** [rizet/skylight#4]
Pardon my misreading of the code earlier, however I realize there is (I believe...) *another* issue I didn't think about at the time.

Char is not guaranteed to be signed. your strcmp function relies on char being signed (To implement the standard behavior) 

Note that this reveals *another* bug relating to signed integer overflow, the actual subtraction must occur inside of `unsigned char`'s 

x86_64 uses two's complement so subtraction is semantically equivalent between signed and unsigned char, but due to language semantics and compiler UB, to get the correct behavior, you have to move the chars into unsigned variables, subtract, move back to signed variables, and return.

Even if you compile with -fwrapv (for defined signed integer overflow) you will still have to correct strcmp to use signed char explicitly instead of just char, as the standard does not specify whether or not char should be signed or not.

**Comment by gek169** [comment]
I'll write you a fix hold up

**Comment by rizet** [comment]
just open a pr

**Comment by gek169** [comment]
```c
signed int my_strcmp(const char* __s1_in, const char* __s2_in) { 
	/*unsigned to guarantee the correct conversions and avoid sign extension.*/
	const unsigned char* __s1 = (const unsigned char*)__s1_in;
	const unsigned char* __s2 = (const unsigned char*)__s2_in;
    for (; *__s1; __s1++) {
		if (*__s1 != *__s2){
			unsigned int __a, __b;
			signed int __a_signed;
			__a = *__s1; /*avoiding sign extension*/
			__b = *__s2;
			__a -= __b;
			/*memcpy(&__a_signed, &__a, sizeof(signed int)); explicit memcpy to avoid conversions*/
			/*OR, if you dont have memcpy/compiling at O0, this should work.*/
			__a_signed = __a;
			return __a_signed;
		}
		__s2++;
	}
	return 0;
}
```
1) I don't want to fork your whole repo just to get strcmp fixed.
2) You probably want all the commits to have your tag

**Comment by gek169** [comment]
if you know how I can make PRs without forking the repo that'd be great, though

**Comment by rizet** [comment]
i didn't know you could explicitly sign, thanks

**Comment by gek169** [comment]
thank you for the code

**Comment by rizet** [comment]
Resolved with 79c6521. If the issue still persists, open a new issue.

**Comment by gek169** [comment]
bad fix, -128 minus one is UB.

**Comment by rizet** [comment]
Further resolution with b7a4753.

**Comment by gek169** [comment]
👍🏻
