### ISSUE TITLE
memcpy stub implementation (I don't know how to do PRs on github, sad face)

### ISSUE THREAD

**Issue by gek169** [rizet/skylight#6]
Please pardon the fact that this isn't actually an issue.

```c
void* skylight_memcpy(void* restrict __dest, const void* restrict __src, size_t __nbytes){
	size_t __i = 0;
	for(;__i<__nbytes;__i++) ((unsigned char*)__dest)[__i] = ((unsigned char*)__src)[__i];
	return __dest;
}
```
Tell me if you see any bugs. I tested it a little bit and I didn't see anything.
This also functions as a memmove implementation... if you remove the restrict qualifiers from the pointers.

Note that this is not a particularly efficient implementation as this will do byte-by-byte copies, the most efficient copying would work in the largest power of two subset of the source which fits into a register. But this works for now

I donate this code to you under the CC0 license and permanently waive all my copyright attachments to this code so that it may be contributed to your codebase and not interfere with its licensing.

**Comment by rizet** [comment]
If you would like to open a PR, follow these steps:

1. Click the "Fork" button in the top right of the repo to fork to a profile/organization.
2. Make the changes you wish and create a commit.
 a. Please remember to make sure that it:
  i. Compiles properly without warnings or errors.
  ii. Commit messages match commit linting rules.
3. On the Code tab, click the Compare button.
4. Clarify you would like to create a pull request.
5. Sit tight as your request is reviewed.

**Comment by gek169** [comment]
well I don't want to fork your whole repo I just want to add one file

**Comment by rizet** [comment]
If you want to make a contribution then you need to fork.

**Comment by rizet** [comment]
You can delete the fork shortly after merging.
