### ISSUE TITLE
Debugging and optimization (-Og and more)

### ISSUE THREAD

**Issue by gek169** [rizet/skylight#7]
I spent a while researching the issues you were having with debugging and optimization, "field optimized out"

You have to keep in mind, that "Field optimized out" is sort of what you *want* to happen. Variables being eliminated is part of the beauty of optimization.

If you really don't want your variables to disappear...
I already told you about the volatile variable trick, that's the oldest trick in the book, however it will defeat a large part of the point of optimization. You *want* things to get eliminated.

1) Don't use GDB, use printf's (Or in your case, putul/putd/puts)  as that guarantees that variables cannot be wholly eliminated at compile time. Failing that, *write it out to a volatile global variable* as that will do the same thing. I know that might sound stupid to you, but I speak from experience, using printfs will help you track down the location of UB and compilation bugs much faster than GDB. Debuggers are overrated.
2) Try to eliminate as much assembly as possible. I noticed you wrote memcpy and memset in assembly... as long as your memcpy and memset implementations don't compile such that they invoke memcpy or memset, then you don't need to worry. I Know that C compilers require memcpy to be implemented, but you can get around that really easily with a bootstrap (Use a memcpy and memset to compile a new memcpy and memset, which is then used in your project). This is important because you may be able to write a more optimized memcpy that operates based on aligned 16/8/4/2/1 byte movs, which you can of course write in assembly, but it'd be hell. You're requiring SSE2, so there's no reason not to. Yes, I believe using optimized loads and stores in a memcpy implementation is important.
3) Try -Os or -Oz (Clang only)... you might be surprised. They're equivalent to -O2 but with some things turned off and extra stuff turned on for more compact bytecode.
4) -mtune=native, it's like -march=native but without the low portability downsides.
5) https://llvm.org/docs/BranchWeightMetadata.html

**Comment by rizet** [comment]
You might not be aware, but `rep movsb` is ***far*** faster than an SSE, or even AVX (excluding 512-bit extensions) memory moves. This is a transparent CPU extension that enhances byte-by-byte memory copies.

**Comment by gek169** [comment]
I did not know that

**Comment by gek169** [comment]
I think since you're probably not going to do anything with this for now you might as well close the issue

**Comment by rizet** [comment]
The issue with fields being optimized out is that I cannot easily check their values while stepping in a debugger.

**Comment by gek169** [comment]
I'd recommend rebuilding with volatile variables or printfs

**Comment by gek169** [comment]
rebuilding takes less than a second on my machine

**Comment by rizet** [comment]
Resolved with 184e70a.
